#version: '3.8'
#
#services:
#  postgresql:
#    build:
#      context: services/postgresql
#      dockerfile: Dockerfile.development
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=bookstore
#      - POSTGRES_PASSWORD=q12345
#    volumes:
#      - "db-data:/var/lib/postgresql/data"
#
#  app:
#    build:
#      context: services/app
#      dockerfile: Dockerfile.development
#      command: java -jar ./app.jar
#      environment:
#        - PORT=8080
#        - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore
##        - - JS_URL=http://localhost
#      image: 'bookstore'
#      ports:
#        - 8080:8080
#      depends_on:
#        - postgresql


version: '3.8'
services:
  app:
    container_name: bookstore3
    image: bookstore3
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: library/postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=q12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookstore
